-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 15:53:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_utilisateur_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `blog`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_id` INT NOT NULL,
  `utilisateurs_id` INT NOT NULL,
  `utilisateurs_role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categorie_id`, `utilisateurs_id`, `utilisateurs_role_id`),
  INDEX `fk_article_categorie_idx` (`categorie_id` ASC) VISIBLE,
  INDEX `fk_articles_utilisateurs1_idx` (`utilisateurs_id` ASC, `utilisateurs_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_categorie`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `blog`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id` , `utilisateurs_role_id`)
    REFERENCES `blog`.`utilisateurs` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateurs_id` INT NOT NULL,
  `utilisateurs_role_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  `articles_categorie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `utilisateurs_id`, `utilisateurs_role_id`, `articles_id`, `articles_categorie_id`),
  INDEX `fk_commentaires_utilisateurs1_idx` (`utilisateurs_id` ASC, `utilisateurs_role_id` ASC) VISIBLE,
  INDEX `fk_commentaires_articles1_idx` (`articles_id` ASC, `articles_categorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id` , `utilisateurs_role_id`)
    REFERENCES `blog`.`utilisateurs` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_articles1`
    FOREIGN KEY (`articles_id` , `articles_categorie_id`)
    REFERENCES `blog`.`articles` (`id` , `categorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`article_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`article_has_tags` (
  `article_id` INT NOT NULL,
  `article_categorie_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `article_categorie_id`, `tags_id`),
  INDEX `fk_article_has_tags_tags1_idx` (`tags_id` ASC) VISIBLE,
  INDEX `fk_article_has_tags_article1_idx` (`article_id` ASC, `article_categorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_has_tags_article1`
    FOREIGN KEY (`article_id` , `article_categorie_id`)
    REFERENCES `blog`.`articles` (`id` , `categorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `blog`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`utilisateurs_has_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`utilisateurs_has_articles` (
  `utilisateurs_id` INT NOT NULL,
  `utilisateurs_role_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  `articles_categorie_id` INT NOT NULL,
  PRIMARY KEY (`utilisateurs_id`, `utilisateurs_role_id`, `articles_id`, `articles_categorie_id`),
  INDEX `fk_utilisateurs_has_articles_articles1_idx` (`articles_id` ASC, `articles_categorie_id` ASC) VISIBLE,
  INDEX `fk_utilisateurs_has_articles_utilisateurs1_idx` (`utilisateurs_id` ASC, `utilisateurs_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateurs_has_articles_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id` , `utilisateurs_role_id`)
    REFERENCES `blog`.`utilisateurs` (`id` , `role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateurs_has_articles_articles1`
    FOREIGN KEY (`articles_id` , `articles_categorie_id`)
    REFERENCES `blog`.`articles` (`id` , `categorie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
