-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 14:18:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema driving_school
-- -----------------------------------------------------
-- a driving_school bdd for driving lessons

-- -----------------------------------------------------
-- Schema driving_school
--
-- a driving_school bdd for driving lessons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `driving_school` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `driving_school` ;

-- -----------------------------------------------------
-- Table `driving_school`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `manual` VARCHAR(45) NULL,
  `license_plate` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`driving_licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`driving_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `cars_id` INT NOT NULL,
  `driving_licenses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_students_cars1_idx` (`cars_id` ASC) VISIBLE,
  INDEX `fk_students_driving_licenses1_idx` (`driving_licenses_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_cars1`
    FOREIGN KEY (`cars_id`)
    REFERENCES `driving_school`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_driving_licenses1`
    FOREIGN KEY (`driving_licenses_id`)
    REFERENCES `driving_school`.`driving_licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`lessons_statements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`lessons_statements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` FLOAT NOT NULL,
  `planned_for` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `teachers_id` INT NOT NULL,
  `lessons_statements_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lessons_teachers_idx` (`teachers_id` ASC) VISIBLE,
  INDEX `fk_lessons_lessons_statements1_idx` (`lessons_statements_id` ASC) VISIBLE,
  INDEX `fk_lessons_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_teachers`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `driving_school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_lessons_statements1`
    FOREIGN KEY (`lessons_statements_id`)
    REFERENCES `driving_school`.`lessons_statements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `driving_school`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `driving_school`.`teachers_has_driving_licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `driving_school`.`teachers_has_driving_licenses` (
  `teachers_id` INT NOT NULL,
  `driving_licenses_id` INT NOT NULL,
  PRIMARY KEY (`teachers_id`, `driving_licenses_id`),
  INDEX `fk_teachers_has_driving_licenses_driving_licenses1_idx` (`driving_licenses_id` ASC) VISIBLE,
  INDEX `fk_teachers_has_driving_licenses_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_teachers_has_driving_licenses_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `driving_school`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_driving_licenses_driving_licenses1`
    FOREIGN KEY (`driving_licenses_id`)
    REFERENCES `driving_school`.`driving_licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
